### ISSUE TITLE
Apply examples on itslanguage.nl website

### ISSUE THREAD

**Issue by kvdb** [itslanguage/itslanguage-js-examples#15]
Should look a bit like this:
https://invis.io/9G78MOZV5#/161788928_-6_Demo_-_Recording

I'm contacting the developer of itslanguage.nl to see how we can include it in the Wordpress site.

**Comment by Lehren** [comment]
Any updates about the Wordpress? I'll probably do it as soon as recognition is finished by @dcsiebe

**Comment by kvdb** [comment]
I think we'll be solving this in a different way.
