### ISSUE TITLE
Write more example documentation

### ISSUE THREAD

**Issue by kvdb** [itslanguage/itslanguage-js-examples#17]
We already have the API docs (http://help-dot-itsl-pilot.appspot.com/api), but that still doesn't show which API calls are useful to you as a developer.
Also, please use the travis hook to publish the docs somewhere. Perhaps on github pages.

**Comment by Lehren** [comment]
Closed in https://github.com/itslanguage/itslanguage-docs/commit/ce42b426c09006e32321a426b996935cde3210db
