### ISSUE TITLE
Add simple recording demo

### ISSUE THREAD

**Issue by Lehren** [itslanguage/itslanguage-js-examples#18]
Add a simple demo to showcase only recording and playback functionality.

**Comment by kvdb** [comment]
The current recordingDemo connects to the localhost backend. This should be the pilot environment like it's set in demo/settings.js, however that setting doesn't seem to be used..

**Comment by Lehren** [comment]
Does it? The current settings.json has the pilot credentials and the connection is made by
```
  const config = {};
  config.apiUrl = settings.API_URL;
  config.wsUrl = settings.API_WS_URL;
  const connection = new its.Connection(config);
```

It gets a token from the pilot GAE.
