### ISSUE TITLE
Deploy on gh-pages

### ISSUE THREAD

**Issue by Lehren** [itslanguage/itslanguage-js-examples#36]
It would be great if the demo environment worked on gh-pages instead of having someone download and run the project by himself. Maybe it's possible.

It looks like something only the project owners can setup.

**Comment by kvdb** [comment]
I enabled github pages on the masterbranch of itslanguage-js-examples (for examples) and itslanguage-js (for docs)
https://itslanguage.github.io/itslanguage-js/
https://itslanguage.github.io/itslanguage-js-examples/

**Comment by remcohaszing** [comment]
This can be automated using travis. Some more stuff may need to be configured by a project owner.
