### ISSUE TITLE
Create challenges admin 

### ISSUE THREAD

**Issue by kvdb** [itslanguage/itslanguage-js-examples#46]
A simple example showing how to create a challenge (recording challenge, analysis challenge and recognition challenge) as an admin, just like we now have examples as if a user performs the challenge.

**Comment by Lehren** [comment]
The way to create anything in the SDK is fairly straightforward for the user/developer it's just a matter of creating a `Challenge` object and passing it to the `createChallenge` method. The parameters are documented what they should be.

Is this really worthy of making another demo page? For that matter there could be a demo page showing how to make Students and Organizations etc.

**Comment by kvdb** [comment]
Well, it would complicate matters on the other demo pages as well (because then you'd need to be able to select a challenge to use it). Perhaps we better focus on the new ELO instead.
